### ISSUE TITLE
Need javax.activation and lucene.queries.intervals

### ISSUE THREAD

**Issue by wimjongman** [eclipse-mylyn/org.eclipse.mylyn#111]
### I can't install in 4.23 because of javax. activation

<details><summary>requires 'java.package; javax.activation [1.2.0,2.0.0)' but it could not be found</summary>
Cannot complete the install because one or more required items could not be found.
  Software being installed: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
  Missing requirement: Old JAXB Runtime 2.3.3.v20221203-1659 (com.sun.xml.bind 2.3.3.v20221203-1659) requires 'java.package; javax.activation [1.2.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Mylyn Commons 3.26.0.N20230320-1407 (org.eclipse.mylyn.commons.notifications.feed 3.26.0.N20230320-1407)
    To: java.package; com.sun.xml.bind 2.3.3
  Cannot satisfy dependency:
    From: Mylyn Context Tasks UI 3.26.0.N20221229-1738 (org.eclipse.mylyn.context.tasks.ui 3.26.0.N20221229-1738)
    To: osgi.bundle; org.eclipse.mylyn.tasks.ui 3.26.0
  Cannot satisfy dependency:
    From: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
    To: org.eclipse.equinox.p2.iu; org.eclipse.mylyn.context.tasks.ui [3.26.0.N20221229-1738,3.26.0.N20221229-1738]
  Cannot satisfy dependency:
    From: Mylyn Tasks UI 3.26.0.N20230221-1933 (org.eclipse.mylyn.tasks.ui 3.26.0.N20230221-1933)
    To: osgi.bundle; org.eclipse.mylyn.commons.notifications.feed 3.26.0
</details>

### Can't install in 4.28 because of  requires 'java.package; org.apache.lucene.queries.intervals 0.0.0' but it could not be found

<details><summary> requires 'java.package; org.apache.lucene.queries.intervals 0.0.0' but it could not be found</summary>
Cannot complete the install because one or more required items could not be found.
Software being installed: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
Missing requirement: Bundle org.apache.lucene : lucene-queryparser 9.5.0 (org.apache.lucene.lucene-queryparser 9.5.0) requires 'java.package; org.apache.lucene.queries.intervals 0.0.0' but it could not be found
Cannot satisfy dependency:
From: Mylyn Task-Focused Interface 3.26.0.N20221229-1738 (org.eclipse.mylyn.context_feature.feature.group 3.26.0.N20221229-1738)
To: org.eclipse.equinox.p2.iu; org.eclipse.mylyn_feature.feature.group [3.26.0,3.27.0)
Cannot satisfy dependency:
From: Mylyn Task List 3.26.0.N20230416-1636 (org.eclipse.mylyn_feature.feature.group 3.26.0.N20230416-1636)
To: org.eclipse.equinox.p2.iu; org.apache.lucene.lucene-queryparser 9.5.0
</details>

**Comment by wimjongman** [comment]
@merks Ed, this is not in simrel. What is your advice?

**Comment by merks** [comment]
Did you leave out the bundle that provides that package from your repo?  I expect this comes from org.apache.lucene.query. 

I can look more closely at home in about .5 hours.

**Comment by merks** [comment]
The lucene.queries bundle is missing looking at the report.   Whatever in the tp provides the other missing package is no doubt also missing from the repo.

**Comment by ruspl-afed** [comment]
My fault, I ought to update category.xml after update of TP, will do so soon
