### ISSUE TITLE
Please let us put the dist.qualifier into a profile and use this in the maven pipeline build.

### ISSUE THREAD

**Issue by wimjongman** [eclipse-mylyn/org.eclipse.mylyn#113]
Please let us put the dist.qualifier into a profile and use this in the maven pipeline build.
We need a default that we can use for a local build and also set the dist.timestampProvider to empty.
Otherwise we can have locale create artifacts that conflicts with artifacts from a staging repository.

_Originally posted by @BeckerFrank in https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/108#issuecomment-1533336944_

**Comment by ruspl-afed** [comment]
We can override [dist.quilifier](https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/mylyn.releng/org.eclipse.mylyn.parent/pom.xml#L57) when running locally. 

Perhaps I do not understand the use case. The problem can appear if we use `mvn install`. But usually `mvn package` or `mvn verify` is well enough for local build. What am I missing?

**Comment by merks** [comment]
I’m not sure I understand either.  I don’t know any projects varying their qualifier. That doesn’t mean none are but none I know of.

**Comment by BeckerFrank** [comment]
I found that part of some previous problems come from the following scenario.

1.  create a local Mylyn workspace and change some code but not committing the changes back to the repository
2. use men clean install to build a local update p2 repository
    with
    `
    <dist.qualifier>'N'yyyyMMdd-HHmm</dist.qualifier>
    <dist.timestampProvider>jgit</dist.timestampProvider>
` the jars get a timestamp from the last commit

3. use file:///... to install this in an other Eclipse Installation using a bundle pool.
4. use the pipeline to build a new nightly/staging version

Now you have in the bundle pool a jar with uncommitted changes but can not overwrite it.

Thougths?

**Comment by BeckerFrank** [comment]
> We can override [dist.quilifier](https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/mylyn.releng/org.eclipse.mylyn.parent/pom.xml#L57) when running locally.
> 
> Perhaps I do not understand the use case. The problem can appear if we use `mvn install`. But usually `mvn package` or `mvn verify` is well enough for local build. What am I missing?

Sure but I find it better when we not hope the someone run mvn without the local change.
So why not that a local default and use a profile in the pipeline builds.

**Comment by merks** [comment]
I see what you mean. Similar things happen sometimes for me with Oomph too.  So you just suggest this for local use not to publish builds to download.eclipse.org with such variations. That seems reasonable.

**Comment by ruspl-afed** [comment]
Do you plan to provide a PR @BeckerFrank ?

**Comment by BeckerFrank** [comment]
> Do you plan to provide a PR @BeckerFrank ?

Now that we have 3.26 and soon 3.26.1 I think we no longer need this.
A work Around is to use an other bundle pool for the Test Eclipse installation.
But if you think we should implement this I can try to create a PR after 3.26.1.

**Comment by BeckerFrank** [comment]
We can implement this if we really need this.
