### ISSUE TITLE
Support a stable repository structure for publishing builds

### ISSUE THREAD

**Issue by merks** [eclipse-mylyn/org.eclipse.mylyn#116]
One approach is to reuse JustJ's repository publishing infrastructure.  I can help integrate that if that's what folks want.  But before investing effort, I want to be **sure** that's really what folks want.  I can provide details here, but for today my time to do that is limited...

Here's one example of how it would work:

https://ci.eclipse.org/emf/job/build/

The build is parameterized:

![image](https://user-images.githubusercontent.com/208716/236128178-2a65c7a1-7907-4bd5-950c-d38875594cf4.png)

The most relevant thing here is that you can specify nightly, milestone, or release and whether to promote the build.  E.g., for a PR build, one does not need to sign, probably shouldn't in fact because it slows down the build and doing that allows a contributor to grab and redistribute signed content with their "hooks" in it, and should not publish it.  

The versions are controlled by the version of a specified/designate feature so one only needs to properly increment feature versions to provide, in the end, new release versions.  One can also control which bundles/features are listed in the documentation; e.g., omit the 3rd party things.

**Comment by merks** [comment]
@ruspl-afed

One problem I will have providing such support (assuming it's what folks want), is that my local build fails at the end like this:

> [INFO] org.eclipse.mylyn.tests 3.26.0-SNAPSHOT ............ FAILURE [  1.392 s]
> [INFO] Mylyn for Eclipse 4.x 3.26.0-SNAPSHOT .............. SKIPPED
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  02:07 min
> [INFO] Finished at: 2023-05-04T08:32:38+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.codehaus.mojo:xml-maven-plugin:1.0.2:transform (default) on project org.eclipse.mylyn.tests: The directory D:\Users\test17\mylyn-main\git\org.eclipse.mylyn\org.eclipse.mylyn.tests\target\surefire-reports, which is a base directory of a ValidationSet or TransformationSet, does not exist. -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   mvn <args> -rf :org.eclipse.mylyn.tests

Any idea what causes this and what I could do to fix it?  I really need to be able to build the p2 update site locally to develop this...

**Comment by ruspl-afed** [comment]
I think this is because of a defect of test result publishing, please have a look here https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/org.eclipse.mylyn.tests/pom.xml#L48
Perhaps we should shift the execution of this goal.

**Comment by ruspl-afed** [comment]
>  I can help integrate that if that's what folks want.

EMF is an outstanding example of a stable and viable component that many people have been using for decades. I would love to introduce its best practices here. 

Let's treat this comment as "that's what folks want" until we get reasoned objections, preferably from Mylyn's active committers.

**Comment by wimjongman** [comment]
Yes. This would be great.

**Comment by merks** [comment]
BTW, you're features use a very small image for Mylyn:

https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/mylyn.commons/org.eclipse.mylyn.commons.core/feature.gif

That's not a problem, but I wonder if there is an SVG version or larger somewhere?

**Comment by ruspl-afed** [comment]
@BeckerFrank @wimjongman  do you have any ideas regarding sources of Mylyn images?

**Comment by BeckerFrank** [comment]
> @BeckerFrank @wimjongman do you have any ideas regarding sources of Mylyn images?

As I know most of the Images are located in org.eclipse.mylyn.tasks.ui and some time back we switch from git to png and provide @2x versions. I do not know any location where other high resolution versions exists.

**Comment by merks** [comment]
I’m almost home and will look in a few minutes.

**Comment by merks** [comment]
I’m almost home and will look in a few minutes.

**Comment by BeckerFrank** [comment]
In org.eclipse.mylyn.releng/bin/create-api-profile.sh we have a shell script for the "old" way creatine the api zip file.

@merks, @ruspl-afed : is this a separate pipeline step or do you think we should integrate this in the maven build?

**Comment by BeckerFrank** [comment]
I have a local mylyn-3.26.0-api.zip but do not know how to upload this to https://download.eclipse.org/mylyn/drops/3.26.0/ so that I can change the Mylyn.setup to that location

**Comment by merks** [comment]
Does a zipped update site work as an API baseline?  I know one can define an API baseline via a *.target file and that can just refer to an update site...

**Comment by merks** [comment]
@BeckerFrank 

I think the build is hung because I forgot another important part of the Jenkins file.  😢  I.e., I think it's hung waiting for the password for genie.mylyn and I need to wrap it like this:
```
sshagent(['projects-storage.eclipse.org-bot-ssh']) {
  ...
}
```
I'll create another PR...

**Comment by BeckerFrank** [comment]
> Does a zipped update site work as an API baseline? I know one can define an API baseline via a *.target file and that can just refer to an update site...

The generated zip filter the updatesite to only contains org.eclipse.mylyn.*.jar and also drops the source jars.
Otherwise we include by example com.google.* or com.apache.* jars in the API Process.

**Comment by merks** [comment]
Yes, I noticed that in the script, but I still wonder if that's 100% essential or just an optimization.  I should look at how the Platform does this...

**Comment by merks** [comment]
Note that I ask about the zipped update site because the publisher produces such a thing already.  The publisher could of course in principle produce an "API" zip driven by another command line argument.

**Comment by merks** [comment]
@BeckerFrank 

I see the platform references its previous released repository:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/a6acb5ba4f80dec506eeb4d4f342e2a72d7f0892/eclipse-platform-parent/pom.xml#L143

And it uses that here:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/a6acb5ba4f80dec506eeb4d4f342e2a72d7f0892/eclipse-platform-parent/pom.xml#L384

Is this the same as what you are wanting to do?

**Comment by BeckerFrank** [comment]
> @BeckerFrank
> 
> I see the platform references its previous released repository:
> 
> https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/a6acb5ba4f80dec506eeb4d4f342e2a72d7f0892/eclipse-platform-parent/pom.xml#L143
> 
> And it uses that here:
> 
> https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/a6acb5ba4f80dec506eeb4d4f342e2a72d7f0892/eclipse-platform-parent/pom.xml#L384
> 
> Is this the same as what you are wanting to do?

No, I want to update the Mylyn.setup file and there the task org.eclipse.oomph.setup.pde.APIBaselineTask to point to a 3.26 api Baseline instead of the https://download.eclipse.org/mylyn/drops/3.25.0/mylyn-3.25.0-api.zip file. This file was generate by org.eclipse.mylyn.releng/bin/create-api-profile.sh and is an updatesite only containing the org.eclipse.mylyn plugins from the updatesite.

**Comment by merks** [comment]
@BeckerFrank 

Maybe it would be good to create a dedicated issue for the baseline thing.   Oomph's setup infrastructure also allows a baseline to be set up using a targlets and this can use the previous release update site directly.  Not only that, it reuses the bundle pool for building the API baseline and it's highly likely that most of the bundles will already be in the pool such that it's hyper fast.  I'm not sure if you care about the details of how the API baseline is set?

@BeckerFrank @ruspl-afed 

The first successful publish has produced the new set of sites:

https://download.eclipse.org/mylyn/updates/

You can inspect the raw underlying file system like this:

https://download.eclipse.org/justj/?file=mylyn/updates/

I made a small mistake in the templates for building the update sites.  Could one of you please manually kick off another nightly build for promotion?

**Comment by merks** [comment]
@BeckerFrank 

On the baseline front, I think one could specify the baseline like this:

![image](https://user-images.githubusercontent.com/208716/236632484-8d4cc3b1-5c9a-4f42-a20a-bd7a6ae63a8b.png)

I.e., just specify the root features, which pulls in the transitive requirements, so this assumes all the plugins are required from these roots.  The URL, once there is a release, will always be the latest release.  So not much ever needs to change, nothing special is needed as input, and it's super fast...

I'm done for the day now.  I'll be around tomorrow and read mail on and off...

**Comment by merks** [comment]
The update site looks good now, though I notice there are no commit links so I'll look at that tomorrow...

Note that one of the bundles has a name that doesn't start with Mylyn:

![image](https://user-images.githubusercontent.com/208716/236633779-68579836-a0df-42a3-b725-5629af279292.png)

I also wonder in general why the tests are in the update site.  Are folks meant to extend, install, or otherwise reuse them?

**Comment by ruspl-afed** [comment]
@BeckerFrank let's discuss baseline issue separately, for me it is also strange that some special script required to produce a baseline while usually one need to reference previous target: either defined "inplace" right in the .setup or referenced.

**Comment by merks** [comment]
I think this is done.  We can open new issues for new issues.
