### ISSUE TITLE
@BeckerFrank let's discuss baseline issue separately, for me it is also strange that some special script required to produce a baseline while usually one need to reference previous target: either defined "inplace" right in the .setup or referenced.

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#127]
@BeckerFrank let's discuss baseline issue separately, for me it is also strange that some special script required to produce a baseline while usually one need to reference previous target: either defined "inplace" right in the .setup or referenced.

_Originally posted by @ruspl-afed in https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/116#issuecomment-1537171768_

**Comment by BeckerFrank** [comment]
For now, we create a separate zip file that contains only the org.eclipse.mylyn.* non source jars.
In the OOMPH setup file Mylyn.setup, we use this zip file to extract the contents to a directory and use that for API analysis.

With @merks solution I got errors 
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/13169360/236665231-c87b8935-01a8-462d-96cb-f2e084f90309.png">

**Comment by ruspl-afed** [comment]
The error looks reasonable, perhaps this is exactly what happened after 3.25.2 or do you think it is false positive?

Error like this may be ignored via Quick Fix, but I'm not sure what was Mylyn policy regarding API and what do we plan to have.

**Comment by merks** [comment]
This was changed:

![image](https://user-images.githubusercontent.com/208716/236867537-91df1e4c-e428-494f-b1de-6c442fadfe0e.png)

https://github.com/eclipse-platform/eclipse.platform.text/pull/107/files#diff-5ca3802af1e4a4276a96aae24aca2a5f7a8d4c5c489fb7364147407a51e544d4

This suggests that the API baseline's version was using a newer version of the platform than you are currently using in your target platform.  In any case, this is not a problem in Mylyn or that can be fixed by Mylyn.

**Comment by ruspl-afed** [comment]
Are we done here @BeckerFrank ?

**Comment by BeckerFrank** [comment]
> Are we done here @BeckerFrank ?

No, I did not create a Quick Fix for the "The minor version should be incremented in version 3.26.1, since execution environments have been changed since version 3.26.0" error in /org.eclipse.mylyn.bugzilla.ide/META-INF/MANIFEST.MF

**Comment by merks** [comment]
Oh yes, I see that pop up occasionally and then I delete the error message. 😜

**Comment by BeckerFrank** [comment]
Fix is in main (#154) so we can close this
