### ISSUE TITLE
Commit Message not automatically populated in Git Stating view

### ISSUE THREAD

**Issue by nbegorre** [eclipse-mylyn/org.eclipse.mylyn#143]
Hi,

I've installed Mylyn 3.26 on a Eclipse 2023-03, I was able to add Tasks repository, and Tasks query, but when I select a task the commit message is not automatically populate.

Here is the list of installed package.
 
![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/44812519/ae4a56f8-1549-4e00-a17a-60b95b3b4f97)

Is it something lost with the revamp of Mylyn ?

**Comment by ruspl-afed** [comment]
Hello @nbegorre. Thank you for the reported issue. 
Could you please post another screenshot to demonstrate where exactly you expect the commit message to be populated?

**Comment by nbegorre** [comment]
Sure, I was used to select a task and to see the commit message into the right part of the git statging view 

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/44812519/3f82dee4-8774-43ab-bcdc-0dc71113a86e)

the commit message is defined in the preferences/Mylyn/Team
![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/44812519/8198416e-83b6-4ba0-90b7-c360273e8510)

**Comment by BeckerFrank** [comment]
Hello @nbegorre,

can you try if one of the following workaround helps.

1) create a new branch from the active branch with "Switch To" -> "New Branch..."
2) collapse the repository in the Git Repositories View
     restart Eclipse
     select the Repository in the Git Repositories View

**Comment by nbegorre** [comment]
Thanks for your reply. I've tried, but the commit message stay blak even after switching to the new branch. I have also try on a new workspace, but still the same situation

**Comment by mjmeijer** [comment]
Please note that in the past this functionality defined in the Mylyn Team connector must actually be implemented in the specific repository connector itself.
Mylyn used to be hosted in eclipse.org git (using git connector) but is now hosted on GitHub (using GitHub connector).
So maybe this functionality is not (yet) implemented in the GitHub connector.

The Github connector was recently 'acquired' by the Mylyn project so it is not yet a first class citizen, so maybe this is just not implemented. I'm traveling so have not time to dig deeper.

**Comment by nbegorre** [comment]
I forgot to mention I was using the trac connector.

I've just tried to reproduce the issue with the Mylyn Eclipse Development Environment, but here, it's working as expected.

I'll continue to dig to understand what could be the root cause this is not working with an exsisting or a new workspace

**Comment by BeckerFrank** [comment]
This is not Connector specific!

we implement the following extension to include the MylynCommitMessageProvider into the egit UI 

`<extension`
`      point="org.eclipse.egit.ui.commitMessageProvider">`
`   <commitMessageProvider`
`         class="org.eclipse.egit.internal.mylyn.ui.commit.MylynCommitMessageProvider">`
`   </commitMessageProvider>`
`</extension>`

With the following steps I am able to get the Commit Message.

1. deactivate the Task
2. make sure that theCommit Message Text box is empty
3. activate the Task
4. switch to an other branch

**Comment by BeckerFrank** [comment]
> Indeed, I think my install is missing the Egit Mylyn UI. I see the mylyn plugin was removed from the version 6.3 of egit https://git.eclipse.org/r/plugins/gitiles/egit/egit/+/refs/heads/stable-6.3 (vs. https://git.eclipse.org/r/plugins/gitiles/egit/egit/+/refs/heads/stable-6.2) and I think this plugin is not available on the mylyn site : https://download.eclipse.org/mylyn/releases/3.26/
> 
> do you think this plugin should be published on the mylyn update site ?

Yes, but I now found that the change is not in 3.26.0 can you please try if https://download.eclipse.org/mylyn/updates/nightly/latest fix your Problem.

**Comment by nbegorre** [comment]
Thanks a million, indeed by using the nightly latest, I was able to add the "Mylyn Git integration - Task focused interface" plugin.

Then all good !
