### ISSUE TITLE
Do we want a new branding image?

### ISSUE THREAD

**Issue by merks** [eclipse-mylyn/org.eclipse.mylyn#145]
Currently this is used as the feature/branding image:

![feature](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/915a35b8-9006-4e8e-a1af-e08c17a56a6a)

It looks a little dated...

For sure I'm no artist, but here's an SVG I whipped up:

![mylyn](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/7aadff7f-322a-479d-8f21-1ec8075900d6)

Here's the corresponding *.png:

![mylyn](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/80c0ffd8-4cef-4842-aacf-fd325f4c7b26)

I'm not sure it's actually better but it's more modern...

What do you guys think?

**Comment by merks** [comment]
Maybe it looks better without color:

![mylyn2](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/345a7075-9f8f-44b1-8a73-f4930a7f1e66)

![mylyn2](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/d8457d71-752f-4a7c-9417-a671af660be2)

**Comment by BeckerFrank** [comment]
@merks: Thank you so much for this!
You are a much better artist than me.
To me the version with the color looks nicer.
I find that the three white lines in the version without color are too dominant.

**Comment by gnl42** [comment]
I think I prefer the white version, feels more like a tribute to mylyns original name, mylar.
But I think I would prefer the white more transparent.

**Comment by merks** [comment]
Yes, I tend to agree that without color it looks a bit more like a transparent sheet.  With this version I used more of a gray color so that the white stripes also have some shading:

![mylyn3](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/0deabc76-ed7f-44ea-9305-e3a9eabfd04c)

![mylyn3](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/39d13bfb-e250-4357-8d56-5129969a59c1)

What do you guys think of this one?

**Comment by mjmeijer** [comment]
I think the 'mylar' should be between the viewer and the eclipse logo. Now the three horizontal bars are in front.
Just having the shiny smooth triangle in front of the eclipse logo is future proof for main eclipse logo evolution

**Comment by merks** [comment]
This is how it looks when it's below the stripes:
![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/5a13de67-002f-47cc-8d47-cc8abd4e8f39)

And this is how it looks when it's above the strips, which is the basis of the image in the preceding comment:
![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/a06c9307-86c4-4c98-9641-d40e0646e55b)

So I don't really know how to address your comment because the bars are not in front.   A darker gray perhaps will help?

**Comment by mjmeijer** [comment]
Maybe use a bit of gradient on the 'sail shape' so the edges have more contrast but it is still shiny.
Alternative add a shade contour  (light from top left) so the eclipse logo is slightly darker locally,
maybe do both

**Comment by merks** [comment]
Recall the original comment about "I'm not artist".  It's worse than that because I don't know how to do the things you suggest.   I copied this shape from an Eclipse Platform SVG and touched it up.  Sorry.  😢  Maybe you know how to do this with Inkscape?

**Comment by BeckerFrank** [comment]
For me it is perfect if we use the last one (it's above the strips)

**Comment by merks** [comment]
FYI, I asked the foundation staff for some professional help and they came up with these, which I think are WAY COOL!

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/4f3468ab-b245-4ce9-91c1-7e874b1462a0)

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/ceeefc78-a2ba-433b-bd6b-f041286862a5)

I'm not sure if they'll be available as SVGs...

**Comment by ruspl-afed** [comment]
> I think both these images are fantastic.

Yes, it's hard for me to choose

**Comment by BeckerFrank** [comment]
> I think both these images are fantastic.

Yes, it's hard for me, but the orange one looks nicer to me.

**Comment by merks** [comment]
It's better than mine by a lot!  😜   But I think the darker colors (e.g., of the stripes) of https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/145#issuecomment-1550731125 are a nicer contrast with the peeling sheet of mylar, and I like the gradient towards lighter in the lower right corner better too...

**Comment by wimjongman** [comment]
Yeah, maybe the foundation staff can take that svg and make some real art out of it? Then at least we have an SVG. The scaled down bitmap will probably not be nice at 32x32 or 16x16

**Comment by wimjongman** [comment]
![mylyn4](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/180969/2067de4f-0f51-4023-9403-1472445143e2)
![mylyn4x64](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/180969/fa550cf5-ff20-48f2-8953-43496be3c16e)
![mylyn4](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/180969/902f7490-7bb0-483c-80b5-7610b15867ac)

**Comment by merks** [comment]
They've promised to give it in SVG format.  That way it's infinitely scalable and we can do cool things with it.  🚀

**Comment by merks** [comment]
It would look great on a T-shirt!

**Comment by wimjongman** [comment]
Ok, in that case I like the colored one. Hard to choose, so I'm fine with either.

**Comment by merks** [comment]
We owe special thanks to https://gitlab.eclipse.org/mekhan and https://gitlab.eclipse.org/sgiacomoni2as for this awesome artwork!

[Eclipse_Mylyn-_Logo.zip](https://github.com/eclipse-mylyn/org.eclipse.mylyn/files/11508598/Eclipse_Mylyn-_Logo.zip)

I will update all the branding images based on this artwork as soon as I'm done the Lucene cleanup...

Probably the website needs some attention too because it looks very stale!

https://github.com/eclipse-mylyn/mylyn-website

**Comment by gnl42** [comment]
Should we push the envelope and see if we can an animated version :)

**Comment by wimjongman** [comment]
@sgiacomoni2as @mekhan Thank you!

**Comment by BeckerFrank** [comment]
> We owe special thanks to https://gitlab.eclipse.org/mekhan and https://gitlab.eclipse.org/sgiacomoni2as for this awesome artwork!
> 
> [Eclipse_Mylyn-_Logo.zip](https://github.com/eclipse-mylyn/org.eclipse.mylyn/files/11508598/Eclipse_Mylyn-_Logo.zip)
> 
> I will update all the branding images based on this artwork as soon as I'm done the Lucene cleanup...
> 
> Probably the website needs some attention too because it looks very stale!
> 
> https://github.com/eclipse-mylyn/mylyn-website

I thought that we use https://git.eclipse.org/r/www.eclipse.org/mylyn.git and yes we should update the site.
The contributors page get an error because we have no bugzilla tickets (all moved to archive).
Btw we should also plan how and when we move the wiki pages see Mail [eclipse.org-committers] Service shutdown plans - update.
Should we open separate Tickets for this?

**Comment by merks** [comment]
I'd like to update all the branding images used for the features but it also seems like a good idea to keep all the original artifacts in the zip file unzipped into a git repository.   Some possible choices are 

https://github.com/eclipse-mylyn/.github
https://github.com/eclipse-mylyn/org.eclipse.mylyn
https://github.com/eclipse-mylyn/mylyn-website

If hosted in the website, one could reference the images without relying on raw access to the images, but the website is pretty stale and I'm not sure the future plans for it...

Thoughts/preferences?

BTW, I think the setup should include a project for mylyn-website.  Also, it seems https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs has kind of split off to have an independent life of it's own, and it can't easily exist in the same workspace because each has a different *.target file.

**Comment by BeckerFrank** [comment]
@merks: If you think we are not finished yet, please reopen with a comment about what is still missing.
