### ISSUE TITLE
Old Guava

### ISSUE THREAD

**Issue by merks** [eclipse-mylyn/org.eclipse.mylyn#159]
I'm not sure what to do about com.google.guava which comes from here and is a really old version restricted to bundle-version="[21.0.0,22.0.0)"  what should we do?    We have old gson and other old things.  How best to update these things?

**Comment by ruspl-afed** [comment]
I would also like to remove guava, but I'm not sure if we can do it right now.

**Comment by merks** [comment]
Yes it’s work to eliminate and at best a no-op. Likely only a small highly stable subset is used such that removing version constraints is okay and expedient.

**Comment by merks** [comment]
Sorry, one test I should have done before is to test installing all the Mylyn features.  This turned up a few problems, like the the rcp thing needing the old logging thing, and not all of the latest guava's dependencies being available.  I will provide a fix for that immediately.
