### ISSUE TITLE
Features in Mylyn that aren't in SimRel

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-mylyn/org.eclipse.mylyn#165]
Hi folks,

I [just added](https://github.com/eclipse-packaging/packages/pull/24) most of the features of SimRel to the EPP, but I found that a bunch of features in the Mylyn update site are not being contributed to SimRel.

On a quick pass AFAICT these items don't appear in SimRel but do appear in [Mylyn](https://download.eclipse.org/mylyn/updates/milestone/S202305240755/) (as contributed to 2023-06 M3):

- org.eclipse.egit.mylyn (xref  #134)
- org.eclipse.mylyn.bugzilla_feature
- org.eclipse.mylyn.commons.activity
- org.eclipse.mylyn.github.feature
- org.eclipse.mylyn.tasks.index

I assume especially the egit and github features are or should one day be part of SimRel and the EPPs.

**Comment by merks** [comment]
I added the 5 selected at the bottom (available features but not contributed to SimRel)  just now, but the other two selected were already present:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/78196c65-9ec0-4fd7-a448-65a8c88c7250)

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/202144

**Comment by jonahgraham** [comment]
Thanks Ed for the quick turnaround - I am reviewing what exactly should be in EPP based on this in https://github.com/eclipse-packaging/packages/issues/19. 

Weird thing is that `org.eclipse.mylyn.github.feature` does not appear in simrel.aggran, I would have expected it around here:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/679236/e72da69e-78ed-4324-ba9d-2e3158e67bc4)

**Comment by jonahgraham** [comment]
I may be going crazy - but `org.eclipse.mylyn.github.feature` doesn't appear in SimRel output https://download.eclipse.org/staging/2023-06/

Is there a SimRel / aggregator issue here preventing it from appearing in the output?

**Comment by merks** [comment]
Yes, there's something crazy going on.  Searching for the name indicates that EGit UI bundle appears to be providing that capability!

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/278db193-4a28-4365-b6f8-00104568e1c3)

@msohn

If I lock in the versions, that likely will help.  I'll get back to you in a few minutes...

**Comment by jonahgraham** [comment]
I am guessing the issue is here: https://git.eclipse.org/r/plugins/gitiles/egit/egit/+/refs/heads/master/org.eclipse.egit.ui/META-INF/p2.inf#10

introduced probably as a way to uninstall mylyn.github when upgrading https://git.eclipse.org/r/c/egit/egit/+/194240

**Comment by merks** [comment]
Yes, only p2.inf could create such a strange capability in a bundle...  I've locked in the version and categorized all the features:

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/202158

So when the aggregation finishes it should be in more sensible shape:

https://ci.eclipse.org/simrel/job/simrel.runaggregator.pipeline/

**Comment by jonahgraham** [comment]
PS The alternative is that egit removes their p2.inf entries, which will resolve most cases, but I don't know long term if that leaves us in a better or worse shape than simply renaming now.

cc @msohn

**Comment by merks** [comment]
I think we need @msohn to explain the purpose of this thing.   Changing IDs is also disruptive...

**Comment by merks** [comment]
What might/could work is to have in the p2.inf of the product a negative requirement on the very specific version provided by EGit's capability:

https://wiki.eclipse.org/Equinox/p2/Customizing_Metadata#Capability_Advice:

**Comment by merks** [comment]
No probably a dumb idea.  I would want to exclude the EGit bundle then and that won't work either...

**Comment by gnl42** [comment]
Dumb question, is there a 'Eclipse for Dummies' book that can help me make sense of this discussion?

**Comment by merks** [comment]
@gnl42 

Sorry, you'd have to learn quite a few concepts around how p2 works and how represents requirements and resolve requirements; I don't know of any good succinct guide for that.  Suffice to say in this case that EGit has made one of its bundles look like it is a feature such that it creates confusion when trying to refer to the actual feature provided by Mylyn.  So either EGit should remove what it did or Mylyn should consider using a different ID for the feature.

**Comment by wimjongman** [comment]
We should probably not be in the egit namespace. Is there time to rename the bundles and features to o.e.mylyn,egit? 

see
https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/18

**Comment by merks** [comment]
I think we've become a bit distracted with renaming org.eclipse.egit.mylyn to org.eclipse.mylyn.egit which is all fine and good but has nothing to do with this issue.  The issue here is that EGit's UI bundle is providing a capability named `org.eclipse.mylyn.github.feature.feature.group` and either it needs to stop doing that or we have to rename the org.eclipse.mylyn.github.feature.feature.group feature.  Note that this is a feature, org.eclipse.mylyn.github.feature.feature.group,  in Mylyn's namespace and there is no compelling reason to rename it other than EGit colliding with it.

**Comment by merks** [comment]
I've pushed this change to Gerrit to address the problem in EGit:

https://git.eclipse.org/r/c/egit/egit/+/202164

**Comment by jonahgraham** [comment]
> I think we've become a bit distracted with renaming org.eclipse.egit.mylyn to org.eclipse.mylyn.egit which is all fine and good but has nothing to do with this issue. 

Yes and no - if both `org.eclipse.egit.mylyn` *and* `org.eclipse.mylyn.github.feature` are renamed that would be ok.

> I've pushed this change to Gerrit to address the problem in EGit:

This is the ideal solution for the 2023-06 release and I hope @msohn has time to review and integrate it. Thanks Ed for submitting it.

**Comment by merks** [comment]
The Gerrit changes for https://git.eclipse.org/r/c/egit/egit/+/202164 are merged, so the RC1 contribution should fix this problem.

**Comment by jonahgraham** [comment]
This seems to be done now, all the features are in and egit have merged in https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/165#issuecomment-1568379730

See https://github.com/eclipse-packaging/packages/pull/26 for the updated contents of what parts of mylyn are in which package.
