### ISSUE TITLE
Actions section of Context tab in task editor too narrow

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-mylyn/org.eclipse.mylyn#170]
The Actions section (see highlighted screenshot below) is too narrow to see everything and I can't see how to change the width.

This screenshot is taken on Linux using EPP for C/C++ 2023-06 M3.

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/679236/7a4efb5b-eccc-498b-9f49-d4088d42875a)

**Comment by jonahgraham** [comment]
I tested on Windows too with 2023-06 M3 EPP for Java developers and it looks the same.

**Comment by gnl42** [comment]
It's been like that for a long time

**Comment by gnl42** [comment]
It seems to a Mylyn mindset. There are far too many hardcoded widths in the code base so you see a lot of truncated text

**Comment by jonahgraham** [comment]
Thanks @BeckerFrank  - the updated layout looks better now:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/679236/703c3155-d084-450c-a0bb-0f58790672c1)
