### ISSUE TITLE
"Appropriate" GitHub connector in mylyn.tasks

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#18]
This Issue was created in the now archived Repository org.eclipse.mylyn.tasks by Maarten Meijer
(see https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/8)

Mylyn philosophy is "eat your own dog food", so now that we moved mylyn to github it makes sense to include a GitHub connector as first class citizen.
Maybe we can invite the current developers as well to participate in mylyn evolution (for example to manage GitHub actions via Mylyn Builds)

**Comment by mjmeijer** [comment]
I cannot do much useful stuff until February I'm afraid

**Comment by BeckerFrank** [comment]
@wimjongman: I did a quick test and it works.
How we want to continue.
Can you run your git migrate script so that we have the repo including the history by example in folder mylyn.connector/tasks/github?

If not we should request the migration to our GitHub Organisation and then run your Script.

After this I can remove the Version constraint from the import packages so that we have a first unable version.

After this we can deside how we can go forward!

**Comment by wimjongman** [comment]
Thomas Wolf said on the Mylyn-dev list:
	
Sat, 7 Jan, 09:35 (13 days ago)
	
to Matthias, Mylyn, EGit
On 06.01.23 22:19 , Matthias Sohn wrote:
> We didn't yet discuss in the EGit project if we want to take up
> maintenance again
> since Mylyn is revived or if we hand it over to the Mylyn project.
>
> @EGit committers: what do you think?

Sure, if Mylyn wants to maintain and improve it, that's perfectly fine
with me. We never did much with it. I think the only new development in
the past couple of years in the Mylyn connector was my changing the
repository set-up dialog to support GitHub PATs better.

However, see below:
* Keep org.eclipse.egit.github.core where it currently is; don't move
   that one to Mylyn.
* Also move org.eclipse.egit.mylyn.ui to Mylyn.

> On Fri, Jan 6, 2023 at 3:46 PM Wim Jongman <[wim.jongman@gmail.com](mailto:wim.jongman@gmail.com)
> <mailto:[wim.jongman@gmail.com](mailto:wim.jongman@gmail.com)>> wrote:
>
>     Matthias, we are moving the EGit GitHub connector into Mylyn. WDYT?
>
>     PR is here:
>     https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/38
>     <https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/38>
>

This PR also copies org.eclipse.egit.github.core, which is **not** part
of the Mylyn connector. It is a completely separate thing and does not
depend on Mylyn or EGit at all.

I would prefer that one to stay where it is, in the
org.eclipse.egit.github repository. Reasons:

1. It is independent.
2. It uses a BREE of JAVA 8 for Android compatibility.
3. It should be versioned, built, tested, and published independently.

In particular it should be published to maven central.

Some technical things:

The connector makes use of EGit internal classes. EGit has removed it
from x-friends in MANIFEST.MF. Expect a lot of PDE warnings about
discouraged accesses.

I would expect that these accesses to internal classes would be analyzed
and be removed eventually. We'd have to figure out what stable APIs EGit
core and UI would have to provide instead.

EGit does not guarantee anything about internal classes.

Bundle org.eclipse.egit.mylyn.ui, which was removed in the EGit
repository in commit 12a21a6c, should probably also be moved to Mylyn.

There, too, we have internal accesses.

Cheers,

   Thomas

**Comment by wimjongman** [comment]
So I am posting this message from the freshly installed Github connector!!!

Get yours via [1] and after that link has expired from [2]

[1] https://ci.eclipse.org/mylyn/job/github-mylyn/view/change-requests/job/PR-56/lastSuccessfulBuild/artifact/org.eclipse.mylyn-site/target/repository/
[2] https://download.eclipse.org/mylyn/snapshots/nightly/mylyn/

**Comment by BeckerFrank** [comment]
> So I am posting this message from the freshly installed Github connector!!!
> 
> Get yours via [1] and after that link has expired from [2]
> 
> [1] https://ci.eclipse.org/mylyn/job/github-mylyn/view/change-requests/job/PR-56/lastSuccessfulBuild/artifact/org.eclipse.mylyn-site/target/repository/ [2] https://download.eclipse.org/mylyn/snapshots/nightly/mylyn/

So we can close this Issue.

**Comment by wimjongman** [comment]
Yes, it is not perfect yet but we can iron that all out later.
