### ISSUE TITLE
Introduce standard "YYY Developer Resources" features that contains source bundles

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn#182]
As discussed [here](https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/168#issuecomment-1567255060) we need to introduce "YYY Developer Resources" features and then remove "SDK" features.

* [x] `org.eclipse.mylyn.builds.sdk` -> `org.eclipse.mylyn.builds.feature.source`
* [x] `org.eclipse.mylyn.commons.sdk` -> `org.eclipse.mylyn.commons.feature.source`
* [x] `org.eclipse.mylyn.context.sdk` -> `org.eclipse.mylyn.context.feature.source`
* [x] `org.eclipse.mylyn.reviews.sdk.feature` -> `org.eclipse.mylyn.reviews.feature.source`
* [x] `org.eclipse.mylyn.sdk_feature` -> `org.eclipse.mylyn.tasks.feature.source`
* [x] `org.eclipse.mylyn.versions.sdk` -> `org.eclipse.mylyn.versions.feature.source`

**Comment by ruspl-afed** [comment]
I would like to do this together with revising feature's content/ids. So, this effort doesn't fit 3.26.1 service release.

**Comment by jonahgraham** [comment]
A new +1 on this - the current SDK bundle has tight requirements on specific Orbit produced third-party bundles. While the MANIFEST.MF's do Import-Package. xref: https://github.com/eclipse/orbit/pull/37

**Comment by ruspl-afed** [comment]
Ed @merks it seems that bundle `org.eclipse.mylyn.commons.net` was included only to SDK feature and now we need to include it to another feature explicitly. I plan to do this tomorrow morning with your review support. If you think that something else should be done before M1 please mention it here.

**Comment by merks** [comment]
Very good. I’m here to help in the morning.

**Comment by ruspl-afed** [comment]
Found another orphan `org.eclipse.mylyn.commons.identity.ui`. Need to check all of them.

**Comment by merks** [comment]
I just started looking as well...

**Comment by ruspl-afed** [comment]
I summarized my findings using #240

**Comment by ruspl-afed** [comment]
Fixed with #238 #240
