### ISSUE TITLE
Remove "discovery" functionality 

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn#196]
Rationale:

* Existing connectors are not compatible with Mylyn 4.0.0+ and needs to be reworked,
* There is no resources to support alternative "marketplace" with Mylyn connectors

We can try to integrate with Eclipse MPC later.

@BeckerFrank @wimjongman @merks  WDYT?

**Comment by ruspl-afed** [comment]
May also close the issue https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/169

**Comment by merks** [comment]
I agree,   We cannot manage some type of parallel connector marketplace.
