### ISSUE TITLE
Releng issue for move to GitHub

### ISSUE THREAD

**Issue by wimjongman** [eclipse-mylyn/org.eclipse.mylyn#2]
Contains various housekeeping commits for the move to GitHub

**Comment by ruspl-afed** [comment]
There is a more specific issue [here](https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/issues/4) and some progress [here](https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/pull/7)
The plan is to fix repos one by one

**Comment by ruspl-afed** [comment]
Fixed with #5

**Comment by ruspl-afed** [comment]
@BeckerFrank it seems that TestSuites were also used for some local testing scenarios. I think we can restore this use case later after merging repositories,
