### ISSUE TITLE
Normalize feature identifiers to simplify support

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn#204]
Currently we have a zoo of feature identifier naming styles that complicates support in general and things like #182 in particular.
The following changes are required (sorted by current name):

* [x] #206
* [x] `org.eclipse.mylyn_feature` -> `org.eclipse.mylyn.tasks.feature`
* [x] #208
* [x] #209
* [x] #210
* [x] #211
* [x] #212
* [x] #213
* [x] #214
* [x] #215 
* [x] #216
* [x] #217
* [x] #218
* [x] #219 
* [x] #220
* [x] #221
* [x] #222
* [x] #223
* [x] #224
* [x] #225
* [x] #226
* [x] #227
* [x] #228

**Comment by merks** [comment]
Changing feature IDs is disruptive for updates and product definitions.  Are you planning p2.inf details to mitigate update migration?

**Comment by merks** [comment]
Changing feature IDs is disruptive for updates and product definitions.  Are you planning p2.inf details to mitigate update migration?

**Comment by ruspl-afed** [comment]
> Are you planning p2.inf details to mitigate update migration?

Yes, I do. Please have a look at [PR](https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/205/files#diff-a739261b17158e3eeb367b8de1e4a0aa329daf391f26979c39ab4a08d5fb1b80R6)

**Comment by ruspl-afed** [comment]
Fixed with #238
