### ISSUE TITLE
target platform strategy

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#22]
This Issue was created in the now archived Repository org.eclipse.mylyn.commons by me
(see https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/issues/14)

**Comment by ruspl-afed** [comment]
This one is done, target aligned with 2022-12 and has no circular dependencies

**Comment by wimjongman** [comment]
Well done! Thank you.
