### ISSUE TITLE
Releng: restore signing

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#24]
This Issue was created in the now archived Repository org.eclipse.mylyn.commons by Alexander Fedorov
(See https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/issues/21)

**Comment by BeckerFrank** [comment]
@ruspl-afed: can we close this. I think you have fixed this with https://github.com/eclipse-mylyn/org.eclipse.mylyn.commons/pull/22

**Comment by BeckerFrank** [comment]
With https://download.eclipse.org/mylyn/snapshots/nightly/mylyn/ I can confirm that signing is restored, so I close this Issue.

**Comment by ruspl-afed** [comment]
Great! Thank you for testing @BeckerFrank
