### ISSUE TITLE
No explicit encoding in Mylyn projects

### ISSUE THREAD

**Issue by sovesti** [eclipse-mylyn/org.eclipse.mylyn#248]
Currently there are 153 projects with no explicit encoding set. It would be good to set UTF-8 encoding in each ```.settings```.

**Comment by ruspl-afed** [comment]
Thank you for your interest in Eclipse Mylyn project @sovesti 

Keeping code base clean is very important for the project health. So, your effort is valuable for us and we can offer another 4.6 thousand warnings in our code base for correction.

Looking forward to further cooperation,
Mylyn Team
