### ISSUE TITLE
java.lang.Boolean constructor is deprecated

### ISSUE THREAD

**Issue by sovesti** [eclipse-mylyn/org.eclipse.mylyn#254]
There are several uses of [deprecated](https://docs.oracle.com/javase%2F9%2Fdocs%2Fapi%2F%2F/java/lang/Boolean.html) ```Boolean(boolean value)``` constructor in Mylyn codebase. It should be replaced with ```Boolean.valueOf(boolean value)```.

**Comment by gnl42** [comment]
Can we just get the Java17 code cleanup/format conventions (#200) settled on and do a global cleanup?

**Comment by BeckerFrank** [comment]
@ruspl-afed: Can we close this ticket? Or is something left?

**Comment by ruspl-afed** [comment]
@sovesti are you done here? If so, please close the ticket.
