### ISSUE TITLE
Restore deactivated tests

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#26]
We have the following disabled tests.
(extracted `org.eclipse.mylyn.team.tests.ChangeSetManagerTest` to another issue https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/312)
- [x] org.eclipse.mylyn.reviews
https://github.com/eclipse-mylyn/org.eclipse.mylyn.reviews/issues/5
- [x] org.eclipse.mylyn.builds
https://github.com/eclipse-mylyn/org.eclipse.mylyn.builds/issues/8
- [x] org.eclipse.mylyn.tasks
https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/6

**Comment by BeckerFrank** [comment]
The Hudson Tests are active again.

The Gerrit Fixture http://mylyn.org/gerrit-2.11.10/ is unavailable and because Eclipse switches from git / Gerrit to gitlab / GitHub we maybe can drop the whole support for Gerrit.
@wimjongman, @ruspl-afed: Thoughts on the topic  drop support for Gerrit.

**Comment by wimjongman** [comment]
Yes, we can drop it.

**Comment by BeckerFrank** [comment]
- https://github.com/eclipse-mylyn/org.eclipse.mylyn.context/issues/9
 can not fixed easily because after drop the CVS Plugin we do no longer have active Change Sets and that is there reason for the failure.
- https://github.com/eclipse-mylyn/org.eclipse.mylyn.reviews/issues/5
 we drop support for Gerrit
- https://github.com/eclipse-mylyn/org.eclipse.mylyn.builds/issues/8
 after activate the test instance (mylyn.org) the testa are now back.
- https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/6
 I think we need to remove the failing tests. Not sure what has changed. But it looks strange that a null URL should open an Editor.

Should we close this Issue?
Thougths?

**Comment by BeckerFrank** [comment]
@wimjongman, @ruspl-afed, @gnl42: I do not know how to fix the open parts.

Can I close this Issue or should we move this issue to the next version?

**Comment by ruspl-afed** [comment]
Moved to 3.27.0

**Comment by BeckerFrank** [comment]
The failing test are deleted with [#70](https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/70) so I mark https://github.com/eclipse-mylyn/org.eclipse.mylyn.tasks/issues/6 as done

**Comment by BeckerFrank** [comment]
@wimjongman, @ruspl-afed: ChangeSetManagerTest are failing because we have removed project org.eclipse.mylyn.team.cvs that used the deprecated org.eclipse.team.internal.ccvs.* Classes;

**Comment by wimjongman** [comment]
Are the test only done with CVS?

**Comment by BeckerFrank** [comment]
> Are the tests only done with CVS?

No, we only have one org.eclipse.mylyn.team.ui.changeSets extension point with an activeChangeSetProvider and that was in the org.eclipse.mylyn.team.cvs project.

The question is:

- Can we remove this function?
- why don't we have this function for the Git version control system?
