### ISSUE TITLE
Changes to the 'Commit Comment Template' are not reflected in the commit message

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#260]
Changes to the 'Commit Comment Template' isn't being honoured by the git commit message box. 

I changed the template to say:
`${task.description} #${task.key}

Task-Url:  ${task.url}`

but the commit message still used the default:
`${task.key}: ${task.description}

Task-Url: ${task.url}`

**Comment by BeckerFrank** [comment]
Are you sure that you changed the right template.
We have a global template in Settings -> Mylyn -> Team and you can overwrite this in a project with properties -> Task Repository -> Commit Template

**Comment by gnl42** [comment]
Sigh, I didn't know about the project setting. Kinda hidden

Can someone please explain the philosophy behind the setup?
We have a dedicated workspace for Mylyn, yet every project has it's own project settings overriding the workspace defaults so we end up with something like #265 when a global setting needs to be changed

**Comment by BeckerFrank** [comment]
> Sigh, I didn't know about the project setting. Kinda hidden
> 
> Can someone please explain the philosophy behind the setup? We have a dedicated workspace for Mylyn, yet every project has it's own project settings overriding the workspace defaults so we end up with something like #265 when a global setting needs to be changed

We have the settings in all projects before we had a workspace for Mylyn. We want to make sure that all Mylyn projects use the same settings and don't want the user to have to make a change to their global settings.

Using the Eclipse installer Mylyn.setup, we can now set the global settings and remove the project specific settings. How do we make sure that each committer / contributor uses the Mylyn.setup

**Comment by gnl42** [comment]
> How do we make sure that each committer / contributor uses the Mylyn.setup

Peer pressure? Don't approve PR?
