### ISSUE TITLE
Upgrade Tycho to version 4.0.3

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#301]
Tycho 4.0.0 requires Maven 3.9.x which is the default for Jenkins so that requirement is met.

**Comment by BeckerFrank** [comment]
[jenkinsbuild 155](https://ci.eclipse.org/mylyn/view/GitHub%20Orga/job/GitHub-mylyn-Orga/job/org.eclipse.mylyn/job/main/155/) is the first run with the new version

**Comment by akurtakov** [comment]
Meanwhile Tycho 4.0.4 is out https://projects.eclipse.org/projects/technology.tycho/releases/4.0.4
