### ISSUE TITLE
Remove guava TypeToken

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#305]
#287 left com.google.common.reflect.TypeToken behind in GerritClient212.

Bugzilla uses com.google.gson.reflect.TypeToken for similar purposes. 

Gerrit unit tests are currently disabled so unable to confirm if the two are functionally equivalent

**Comment by gnl42** [comment]
@BeckerFrank I saw you used the gson version in your GitLab code, any thoughts on this one?

**Comment by BeckerFrank** [comment]
> @BeckerFrank I saw you used the gson version in your GitLab code, any thoughts on this one?

Yes, we use Gson and thus com.google.common.reflect.TypeToken to convert the REST responses from Bugzilla Rest and Gitlab Connector. This is also used in Common SDK for the test configuration.

If we should no longer use Gson what should we use for serialization and deseralisation?

**Comment by gnl42** [comment]
I meant any thoughts on this issue.

Can I replace the guava TypeToken with the gson TypeToken in GerritClient212?

It's the remaining guava use Mylyn

**Comment by BeckerFrank** [comment]
> I meant any thoughts on this issue.
> 
> Can I replace the guava TypeToken with the gson TypeToken in GerritClient212?
> 

Yes, that should work
