### ISSUE TITLE
Replace guava MediaType

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#306]
#287 left Multimap/MediaType behind in TaskEditorExtensions

Can it be replaced by javax.ws.rs.core.MediaType?

**Comment by merks** [comment]
Check if there is a jakarta equivalent too.

**Comment by gnl42** [comment]
jakarta.ws.rs.core.MediaType

**Comment by gnl42** [comment]
The main difference that I can see is that guava would allow "a=1,a=2" whereas ws.rs would just accept "a=", not sure if "1" or "2"
