### ISSUE TITLE
Clean up java code

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#309]
With the new 'Clean Up..' code style settings in place, how should we apply them to the code base?

See #311 poll

**Comment by akurtakov** [comment]
FYI, if you make it a discussion you can have a real poll as described at https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/participating-in-a-discussion#creating-a-poll

**Comment by gnl42** [comment]
Thanks. So much to learn

**Comment by gnl42** [comment]
Done with #375, ##376, #377, #378, #379. #380, #381, #382, #383, #384, #385
