### ISSUE TITLE
Move Mylyn Doc Task Editor Integration to the Mylyn Repository

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#313]
From now on we will have the Task Editor Integration no longer in the Mylyn Docs Repository. 

Details can be found in https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/issues/131

**Comment by ruspl-afed** [comment]
Now Mylyn Docs is a part of Mylyn repository
