### ISSUE TITLE
The Help -> Report Bug or Enhancement is effectively useless

### ISSUE THREAD

**Issue by merks** [eclipse-mylyn/org.eclipse.mylyn#338]
It's empty:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/208716/4444da20-aedc-41fa-8c0f-0a8ab60e354e)

so not only kind of unless, it creates a bad impression:

https://www.eclipse.org/forums/index.php/mv/msg/1114126/1862577/#msg_1862577

**Comment by BeckerFrank** [comment]
@merks , @nitind : Currently there is only one provider in org.eclipse.mylyn.bugzilla.ide (see the definition of the extension point in plugin.xml).
The way this is implemented allows us to disable the action if no providers are defined. But this code is called too late, so you have to select the action and then get an information dialog with the text "The chosen operation is not enabled". Is this a better solution?

**Comment by BeckerFrank** [comment]
> Anything that's in the menu and looks inviting but then is useless is probably going to make people shake their heads...

This is only useless as long as you not install the Bugzilla feature. In the plugin.xml are the following Products defines
<img width="602" alt="Bildschirmfoto 2024-01-10 um 18 09 42" src="https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/13169360/e249f92f-ab4a-4365-944d-cab978d0e03d">
If you select one you end up with a new Bugzilla Ticket and prefilled some fields.

Should we 

-  remove this complete 
- add a similar function to GitHub and later GitLab connector if possible

**Comment by ruspl-afed** [comment]
There should be a special table item "Install more providers... ", acting as a launcher for install action

**Comment by merks** [comment]
@jonahgraham  Given bugzilla at eclipse is on the way out, we should not have the in packages if it typically useless.

**Comment by jonahgraham** [comment]
+1 to removing it - I will create a bug to review and figure out how to remove from EPP if it is still there later in the release cycle. https://github.com/eclipse-packaging/packages/issues/102

FWIW it is equally as dated as the Help -> Contribute that directs to https://www.eclipse.org/contribute/ which is mostly simply dated. https://github.com/eclipse-packaging/packages/issues/103

**Comment by ruspl-afed** [comment]
Why bugzilla outage should be a reason to remove this functionality at all? Let's reroute it to GitHub and GitLab where Eclipse projects are hosted now, as suggested by @BeckerFrank above.

**Comment by merks** [comment]
We only mention that because the comment was that bugzilla was the only provider.  If there is GitHub/GitLab that would be helpful!

**Comment by ruspl-afed** [comment]
@jonahgraham I did a reroute for Mylyn, Platform and PDE from Bugzilla to GitHub and this is a part of Mylyn 4.2.0 M2 contribution to SimRel.
Perhaps it can commute the sentence from EPP side.

**Comment by jonahgraham** [comment]
> Perhaps it can commute the sentence from EPP side.

Yes! and wonderful. https://github.com/eclipse-packaging/packages/issues/102

**Comment by ruspl-afed** [comment]
Thank you @jonahgraham for verification! 
Please note, that for GitHub we have only these Eclipse Projects where I have committer role and know for sure how to submit an issue. Others require additional investigation to understand the status of migration from Bugzilla.

I hope we can close this one @merks  and open others for particular Eclipse Project to appear in the wizard.

**Comment by merks** [comment]
Great job. 👏🏿
