### ISSUE TITLE
Replace dependency to org.eclipse.osgi.services

### ISSUE THREAD

**Issue by HannesWell** [eclipse-mylyn/org.eclipse.mylyn#339]
The bundle `o.e.osgi.services` is deprecated for removal as part of https://github.com/eclipse-equinox/equinox/issues/18 and already has been changed to be empty and only re-export the 'official' OSGi artifacts published to Maven-Central.
It should be replaced by imports of the desired `org.osgi.service.*` packages so that the runtime can choose a suitable provider independently of the bundle name.

**Comment by merks** [comment]
Note that if one needs to ensure that a package satisfying any particular requirement is actually available in the project's update site, one can only do that by specifying a bundle name in some feature or directly in the category.xml.  In other words, it seems not always possible to avoid using bundle names completely...

**Comment by HannesWell** [comment]
> Note that if one needs to ensure that a package satisfying any particular requirement is actually available in the project's update site, one can only do that by specifying a bundle name in some feature or directly in the category.xml.

In general one could also express a generic requirement (that's e.g. not a package) via a `Require-Capability`:
https://docs.osgi.org/specification/osgi.core/8.0.0/framework.module.html#framework.module.dependencies

Then you could configure Tycho to include all dependencies in a built p2-repo, but remove artifacts provided in other p2-repos listed in the Target-Platform and add those repositories as references.
With that one gets a self-contained repository of minimal size, like for example in m2e:
https://github.com/eclipse-m2e/m2e-core/blob/e2d17cd18af656d08c6e6017b08444ff929e4e9f/org.eclipse.m2e.repository/pom.xml#L53-L66

**Comment by ruspl-afed** [comment]
Thank you for your care about Eclipse Mylyn @HannesWell 
I found 3 bundles that requires `org.eclipse.osgi.services` bundle and moved them to Import-Package with #340
