### ISSUE TITLE
Prepare contribution for SimRel 2024-03 M1

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn#350]
We need to prepare contribution for SimRel 2024-03 M1

- [x] align target platform
- [x] assembly stable build
- [x] update contribution

**Comment by ruspl-afed** [comment]
@merks @jonahgraham
Initially my plan was to contribute [federated Mylyn(+Docs) solution](https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/347) for M1, but it still needs more work.

However, I still have a hope to contribute federated Mylyn after 2024-03 M1, and it will have the following breaking changes:
* all versions aligned with Mylyn, i.e. 4.2.0
* all feature identifiers modified to `org.eclipse.mylyn.*.feature` form
* all modules with `MANIFEST.MF` converted to `eclipse-plugin` packaging
* dedicated test bundles extracted where needed

I know, that people don't like changes, but today this unification is the only form to keep the Mylyn contribution alive and actual.
For these who would like to see Mylyn Docs supported, but without so annoying breaking changes there are two options:
* contribute effort to keep "maintains" branches
* fill Mylyn project with support budget

**Comment by jonahgraham** [comment]
As discussed on our call today, I like the timing of contributing the "breaking" change just after M1 on Friday so we have time to test and deal with it before M2 (as opposed to everyone working late to get it into M1)

> * all versions aligned with Mylyn, i.e. 4.2.0

This part has been contributed for M1 in #157?

**Comment by ruspl-afed** [comment]
> This part has been contributed for M1 in https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/157?

I think you mean https://github.com/eclipse-simrel/simrel.build/pull/157
Yes, the most of versions were changed with https://github.com/eclipse-mylyn/org.eclipse.mylyn/commit/99476861370bc016d87fef599530ebf2d424ef5f , but then a found a few IUs that needs alignment

**Comment by merks** [comment]
Which things actually have new feature IDs?

**Comment by ruspl-afed** [comment]
Preliminary list is 
* `org.eclipse.mylyn.docs*`
* `org.eclipse.mylyn.wikitext*`
* `org.eclipse.mylyn.htmltext*`

The final list will be provided a bit later, after I can see it green at Jenkins

**Comment by merks** [comment]
I see.  It's a short list and of course just the stuff that was migrated from Mylyn Docs.

**Comment by ruspl-afed** [comment]
Yes, only the Mylyn Docs part that was recently put in the Mylyn repository without too much care about releng aspect

**Comment by ruspl-afed** [comment]
> Preliminary list is
> 
> * `org.eclipse.mylyn.docs*`
> * `org.eclipse.mylyn.wikitext*`
> * `org.eclipse.mylyn.htmltext*`

Created an issue https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/356
