### ISSUE TITLE
Archive old Mylyn repositories

### ISSUE THREAD

**Issue by wimjongman** [eclipse-mylyn/org.eclipse.mylyn#36]
We are using a lot of data. I suggest archiving all old releases:

https://download.eclipse.org/mylyn/

**Comment by ruspl-afed** [comment]
Ed @merks we have 0.5G used by "updates" already. Do you have any policies how to archive the output of this build procedure?

**Comment by merks** [comment]
Here’s your footprint on the mirrors 

https://download.eclipse.org/oomph/archive/eclipse/mylyn/index.html

I think you need not worry for a few years about the updates folder.   Mylyn as a whole is .13 % so I would not fuss so much.

**Comment by BeckerFrank** [comment]
@wimjongman: I think we can close this! If not please reopen this issue.
