### ISSUE TITLE
Gitlab connector

### ISSUE THREAD

**Issue by wimjongman** [eclipse-mylyn/org.eclipse.mylyn#37]
We need to connect GitLab.

See https://github.com/pweingardt/mylyn-gitlab/issues/61

**Comment by bgranier** [comment]
Hi,
To anwser to the question asked here : https://github.com/pweingardt/mylyn-gitlab/issues/61#issuecomment-1373426635 .

Unfortunately, not. I am teaching and this connector is "just" a way to show to students how to manage issues. So I can not do a donation.

Best regards,

Bernard

**Comment by mjmeijer** [comment]
@bgranier question was not to make monetary donation, but @wimjongman asked would you donate this `code` to the revived mylyn project as an example connector? JIRA and Trac seem a bit out of date nowadays.

**Comment by bgranier** [comment]
humm you mean "to give me" the code in order to revive it to get a runnable plugin ?

Why not, but i am not sure that i will have the time for that.

**Comment by BeckerFrank** [comment]
> humm you mean "to give me" the code in order to revive it to get a runnable plugin ?
> 
> Why not, but i am not sure that i will have the time for that.

No we need to ask the maintainer of the Repository (https://github.com/pweingardt) if we get the permission to include a copy of the source into the new eclipse.mylyn GitHub organisation.

**Comment by gnl42** [comment]
I think we can close this one

**Comment by BeckerFrank** [comment]
> I think we can close this one

I haven't received any feedback from [pweingardt] (https://github.com/pweingardt), so I think we should create a new mylyn Task Connector for Gitlab.

I have created the not officially supported Bugzilla REST Connector, so I know how to implement a Task Connector.

Should I start developing an MVP version?

**Comment by wimjongman** [comment]
Sorry for the confusion. Let me try to explain my request a bit better.

It looks like you have built a connector for GL. We think a GL connector is important.

Indeed, my request was not for money (thanks Maarten), but for your code. I should have called it code contribution and not donation. Sorry for the confusion.

If you want, you can become an Eclipse Mylyn committer and help maintain the connector.

We did not look at your code yet, so I am not sure if it is even possible.

Some of the things that should happen are:

* You have to license the code under EPL
* Your code has to move to the org.eclipse namespace.
* You have to sign the eclipse contributor agreement and declare that all the copyright of the code belongs to you and that you contribute the code to the open source.

There are probably a couple of other things that I have forgotten but these are the basics.

**Comment by BeckerFrank** [comment]
I have developed a Gitlab Connector Preview that can display tasks and process simple queries (all based on the REST API).
Currently, no update is possible.
Should I move this state to a branch so we can start a discussion?

I have tried this with gitlab.com and not with the Eclipse Gitlab instance. For the eclipse instance we need to implement a different autentification.

What do you guys think about this?

**Comment by wimjongman** [comment]
Nice! Yes, please push to a branch.

What are the auth differences? We can't log in with a token on both instances?

**Comment by BeckerFrank** [comment]
> Nice! Yes, please push to a branch.

This is work in progress which is not production quality
https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/new/37_gitlab_connector

> What are the auth differences? We can't log in with a token on both instances?

Actual I only implement the [oauth owner password](https://docs.gitlab.com/ee/api/oauth2.html#resource-owner-password-credentials-flow) login and this did not work for me with [Eclipse Gitlab](https://gitlab.eclipse.org)

**Comment by BeckerFrank** [comment]
@wimjongman: Can we close this issue?

**Comment by wimjongman** [comment]
Yes! Thanks Frank!!
