### ISSUE TITLE
cleanup maven build

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#440]
In mylyn.docs we have taken over some parts from the time when this was a separate repository with a separate build. These are now to be deleted.

**Comment by ruspl-afed** [comment]
what exactly do you mean here?

**Comment by BeckerFrank** [comment]
> what exactly do you mean here?

I think we can remove the /mylyn.docs/.mvn/extensions.xml and also the .github folder

**Comment by ruspl-afed** [comment]
we can either wait or degrade something intentionally.
but I would better wait until release 4.2.0, then we can play with it.

**Comment by BeckerFrank** [comment]
I think we're done.
