### ISSUE TITLE
RepositoryLocationPart doesn't accept "http://" as a valid URL

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#45]
While trying to get the Jenkins connector to talk to my local Jenkins instance I found a bad check for a valid URL

**Comment by wimjongman** [comment]
Thanks, George! Are you testing the latest builds?

**Comment by gnl42** [comment]
Hi Wim,
    local build from main.

I have no idea how the Eclipse build process works, or where to find the 
builds

     George
