### ISSUE TITLE
Remove Subclipse integration from distribution 

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn#47]
Currently we have IP issues with `org.tigris.subversion` bundles that blocks our CI and could be a blocker for release as well.
see https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6864
see https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/6865

Let's remove Subclipse integration from our distribution. 

As the next step we can consider 

switching to EF-hosted Subversive https://www.eclipse.org/subversive/ (nope, it is not fully dead, we did a release recently https://projects.eclipse.org/projects/technology.subversive/releases/4.8.0)

or other options.

WDYT @wimjongman @BeckerFrank ?

**Comment by wimjongman** [comment]
Sounds great. Are you feeling better?

@BeckerFrank can I go ahead with the github integration?

**Comment by ruspl-afed** [comment]
> Are you feeling better?

Thank you for asking, Wim! It is better now, but still actual.
So I plan to create a PR that should unblock our pipelines.

**Comment by BeckerFrank** [comment]
Done with pull request #48
