### ISSUE TITLE
eclipse so stupid

### ISSUE THREAD

**Issue by AucT** [eclipse-mylyn/org.eclipse.mylyn#481]
I tried to use eclipse php 2024-3. My first 3 minutes using it

bugs:

1) run as php locl server will run my file in browser http://localhost:8605/ProjectName/form1.html

instantly get 404 error, because url should be  http://localhost:8605/form1.html

UI is more complex than rocket science. I don't know if it can be fixed in settings

2) Running through server
Can't easily stop. When I run again getting lag for 5 seconds and then error that port is already in use....

3) after trying to fix it something probably broke. i deleted some weird folder servers no no way to add it back again and getting "The Tomcat server configuration at \Servers\PHP Built-in Server at localhost-config is missing. Check the server for errors."

back to phpstorm :(

**Comment by akurtakov** [comment]
And you have reported to totally unrelated project ?!?! At least first part of your report should go to https://github.com/eclipse-pdt/pdt after significant rewording to get proper details what/how/where so if there is anyone interested in reading a report with such title can actually act on it.
I also encourage you to read https://www.eclipse.org/org/documents/Community_Code_of_Conduct.php so you can communicate better next time.
As Mylyn has nothing to do with PHP and/or Tomcat closing this one.

**Comment by AucT** [comment]
yeah sorry, I shouldn't write this rant. Just it is very frustrating to get in so much trouble for simple tasks.
Del this issue. not needed anymore.
