### ISSUE TITLE
When will the new version be released from main

### ISSUE THREAD

**Issue by azaylamba** [eclipse-mylyn/org.eclipse.mylyn#49]
Hi,

I am facing an issue while using mylyn notifications feed plugin with Java11. The issue is occurring due to required bundle javax.xml.bind in org.eclipse.mylyn.commons.notifications.feed in version 3.25.2 and 3.26 as well. My project has required dependency on jakarta.xml.bind. So now both these dependencies are causing issue during resolution of javax.xml.bind package.

This is already handled in main branch https://github.com/eclipse-mylyn/org.eclipse.mylyn/blob/main/mylyn.commons/org.eclipse.mylyn.commons.notifications.feed/META-INF/MANIFEST.MF where javax.xml.bind is not a required dependency.

So, just want to know when the next version from main will be released. Contributing guidelines seems out of date, so not sure how I can I raise a PR for new branch as well.

Can someone please help me on this?

Regards,
Ajay.

**Comment by BeckerFrank** [comment]
Here you find the Issue for the next [planed release 3.26](https://github.com/eclipse-mylyn/.github/issues/5).
And this are the not yet fixed Issues planned for [Mylyn 3.26.0](https://github.com/eclipse-mylyn/org.eclipse.mylyn/milestone/1).

Contributions are Wellcome.
[Here](https://github.com/eclipse-mylyn/.github/blob/main/CONTRIBUTING.md) you find how to setup a Development Setup using the Eclipse-Installer.

**Comment by gnl42** [comment]
You can work around the problem by placing a copy of com.sun.xml.bind_2.2.0.v20201118-1845.jar in the eclipse/plugins folder

**Comment by azaylamba** [comment]
> You can work around the problem by placing a copy of com.sun.xml.bind_2.2.0.v20201118-1845.jar in the eclipse/plugins folder

Hi @gnl42, Our project is RCP project where the dependencies are resolved via target definition. There is no entry for javax.xml.bind in the target definition but it is getting downloaded via org.eclipse.mylyn.commons.notifications.feed. So I cannot manually change the plugins in the build. And com.sun.xml.bind_2.2.0.v20201118-1845.jar is already there in the plugins folder.
I think issue here is required dependency of javax.xml.bind in org.eclipse.mylyn.commons.notifications.feed

**Comment by azaylamba** [comment]
For reference, below is the exception thrown:

`org.osgi.framework.BundleException: Could not resolve module: org.eclipse.mylyn.tasks.ui [423]
  Unresolved requirement: Require-Bundle: org.eclipse.mylyn.commons.notifications.feed; bundle-version="1.0.0"
    -> Bundle-SymbolicName: org.eclipse.mylyn.commons.notifications.feed; bundle-version="1.17.2.v20200813-0821"; singleton:="true"
       org.eclipse.mylyn.commons.notifications.feed [400]
         No resolution report for the bundle.  Bundle was not resolved because of a uses constraint violation.
  org.apache.felix.resolver.reason.ReasonException: Uses constraint violation. Unable to resolve resource org.eclipse.mylyn.commons.notifications.feed [osgi.identity; osgi.identity="org.eclipse.mylyn.commons.notifications.feed"; type="osgi.bundle"; version:Version="1.17.2.v20200813-0821"; singleton:="true"] because it is exposed to package 'javax.xml.bind' from resources javax.xml.bind [osgi.identity; osgi.identity="javax.xml.bind"; type="osgi.bundle"; version:Version="2.2.0.v201105210648"] and jakarta.xml.bind [osgi.identity; osgi.identity="jakarta.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"] via two dependency chains.

Chain 1:
  org.eclipse.mylyn.commons.notifications.feed [osgi.identity; osgi.identity="org.eclipse.mylyn.commons.notifications.feed"; type="osgi.bundle"; version:Version="1.17.2.v20200813-0821"; singleton:="true"]
    require: (&(osgi.wiring.bundle=javax.xml.bind)(bundle-version>=2.2.0))
     |
    provide: osgi.wiring.bundle: javax.xml.bind
  javax.xml.bind [osgi.identity; osgi.identity="javax.xml.bind"; type="osgi.bundle"; version:Version="2.2.0.v201105210648"]

Chain 2:
  org.eclipse.mylyn.commons.notifications.feed [osgi.identity; osgi.identity="org.eclipse.mylyn.commons.notifications.feed"; type="osgi.bundle"; version:Version="1.17.2.v20200813-0821"; singleton:="true"]
    require: (&(osgi.wiring.bundle=com.sun.xml.bind)(bundle-version>=2.2.0))
     |
    provide: osgi.wiring.bundle; bundle-version:Version="2.3.3.v20201118-1818"; osgi.wiring.bundle="com.sun.xml.bind"
  com.sun.xml.bind [osgi.identity; osgi.identity="com.sun.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
    import: (&(osgi.wiring.package=javax.xml.bind)(&(version>=2.3.3)(!(version>=2.3.4))))
     |
    export: osgi.wiring.package: javax.xml.bind
  jakarta.xml.bind [osgi.identity; osgi.identity="jakarta.xml.bind"; type="osgi.bundle"; version:Version="2.3.3.v20201118-1818"]
	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1786)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1672)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)`

**Comment by ruspl-afed** [comment]
> Our project is RCP project where the dependencies are resolved via target definition

so, what if you add com.sun.xml.bind to the mentioned target definition?

**Comment by azaylamba** [comment]
> so, what if you add com.sun.xml.bind to the mentioned target definition?

It is already added. If you see the exception above, the problem is due to presence of javx.xml.bind and jakarta.xml.bind both of which have package javax.xml.bind.
I cannot remove jakarta.xml.bind because it is required by other plugins to run on Java 11

**Comment by ruspl-afed** [comment]
New version is published: https://download.eclipse.org/mylyn/releases/3.26/
