### ISSUE TITLE
Unable to Add GitHub Gist as Task Repository

### ISSUE THREAD

**Issue by emecas** [eclipse-mylyn/org.eclipse.mylyn#491]
### Versions:

1) Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2024-03 (4.31.0)
Build id: 20240307-1437

2) Eclipse IDE for Enterprise Java and Web Developers	4.31.0.20240307-1200	epp.package.jee	Eclipse Packaging Project

3) Mylyn Tasks Connector: GitHub	6.4.0.v20240209-1319	org.eclipse.mylyn.github.feature.feature.group	Eclipse Mylyn

### Problem : 

I'm encountering an error when attempting to add a new task repository of type "GitHub Gist." Regardless of the URL format used, I receive the message: `Enter a valid server URL.`

Here are the specific URLs I've tried (replacing <my-github-user> with my actual username):

    https://gist.github.com (Base URL)
    https://gist.github.com/<my-github-user> (My User Gists)
    https://gist.github.com/<other-valid-github-user> (Another User's Gists)
    https://gist.github.com/discover (Discover Gists)

Additionally, I have attempted using:

    Valid user credentials (username and password)
    Valid access token

Unfortunately, using any of these options prevents the expected functionality. The buttons "Validate Settings" and "Finish" remain disabled.

### How to reproduce:

1. Go to the contextual menu in the `Task List` tab, then click `New` and then `Query...`

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/849502/f9cffcaa-981f-45b5-ad2d-b6ed8b66ac50)

2. in the emergent dialog, click in `Add Task Repository` button, and then select from the list `GitHub Gist` and then click the`Next` button

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/849502/ed1c3678-62d7-4d8b-8b49-ef15e38ba836)

3. Here is the problem

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn/assets/849502/f456e2b7-3fcf-419a-a050-412b92788ddd)

**Comment by BeckerFrank** [comment]
This is not easy to fix. We have taken over responsibility from another project. As far as I can see, the problem is that the gist URL is validated with org.eclipse.egit.github.core.RepositoryId.createFromUrl. Gist URLs have no owner and no name segment like repositories. I don't know how this has ever worked.

**Comment by emecas** [comment]
> This is not easy to fix. We have taken over responsibility from another project. 

Do you mean that you are barely taking ownership of this project, I guess?

> As far as I can see, the problem is that the gist URL is validated with org.eclipse.egit.github.core.RepositoryId.createFromUrl. Gist URLs have no owner and no name segment like repositories. 

Where is the code you are referring too Here? I would like to take a look, may you facilitate a link?

> I don't know how this has ever worked.

@BeckerFrank thank you for following up on the subject. It was my first time trying to use it. Maybe they made it available but non-functional

**Comment by emecas** [comment]
@BeckerFrank thank you for the fix, I saw you closed this and labeled for 4.3.0 , any idea when it is going to be available?

**Comment by BeckerFrank** [comment]
> @BeckerFrank thank you for the fix, I saw you closed this and labeled for 4.3.0 , any idea when it is going to be available?

The change was in Commit https://github.com/eclipse-mylyn/org.eclipse.mylyn/commit/58da8beda7f73e6c7eaf842bb78442500787ccd5 and is part of the now available Version 4.3.0. If not please open a new Issue.

**Comment by emecas** [comment]
> > @BeckerFrank thank you for the fix, I saw you closed this and labeled for 4.3.0 , any idea when it is going to be available?
> 
> The change was in Commit [58da8be](https://github.com/eclipse-mylyn/org.eclipse.mylyn/commit/58da8beda7f73e6c7eaf842bb78442500787ccd5) and is part of the now available Version 4.3.0. If not please open a new Issue.

Verified, it is working, I had to upgrade to 2024-06 (4.32.0) Build id: 20240606-1231, Thanks @BeckerFrank again for the fix!!
