### ISSUE TITLE
Task 'Activate/Deactive' "button" disappears when a task is refreshed

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#50]
The task 'Activate/Deactive' "button" is present when one first opens a task, but as soon as you refresh the task, the button disappears

![image](https://user-images.githubusercontent.com/66577321/216558258-0bbceb1c-f4a2-42fd-90e9-e2348db54ef6.png)
![image](https://user-images.githubusercontent.com/66577321/216558338-cf595196-4591-4d9f-bec7-0050128d0e75.png)

**Comment by BeckerFrank** [comment]
> The task 'Activate/Deactive' "button" is present when one first opens a task, but as soon as you refresh the task, the button disappears
> 
> ![image](https://user-images.githubusercontent.com/66577321/216558258-0bbceb1c-f4a2-42fd-90e9-e2348db54ef6.png) ![image](https://user-images.githubusercontent.com/66577321/216558338-cf595196-4591-4d9f-bec7-0050128d0e75.png)

@gnl42: Please give some more information. The images make it not clear if this is from the Task Editor or some other place.
In my environment the icon is not a square but a circle.
Do you meen this (red underlined icon)?
![image](https://user-images.githubusercontent.com/13169360/217608295-e2bf9b5d-46af-4485-9b39-cb48bab6e3a1.png)

**Comment by gnl42** [comment]
Sorry, bad capture. 

Yes, that is the one.

**Comment by BeckerFrank** [comment]
I found that this is a layout problem 
![image](https://user-images.githubusercontent.com/13169360/218005668-fedbfda4-7c02-4f0c-994b-52f568226ec2.png)
The icon is behind the bug number text.
@gnl42 : can you verify that this is the same in your environment?
@wimjongman: should I set the milestone to 3.26?

**Comment by wimjongman** [comment]
Hi Frank. You can set the milestone if you expect this to be worked on. We should probably discuss our administration a bit. Maybe we can have a conference call next week together with @ruspl-afed to talk about various things.

**Comment by BeckerFrank** [comment]
The fix is in https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/52
