### ISSUE TITLE
launch files expect JavSE-1.6

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#53]
The *.launch files wants JavaSe-1.6 and (removed parameters `-XX:PermSize=128m -XX:MaxPermSize=256m`

JavaSE-11 is the minimum needed for the current Eclipse/Mylyn combination to run/debug the code.

**Comment by akurtakov** [comment]
Please note that 4.28 (2023-06) Eclipse Platform will require Java 17 so I would vote for Mylyn setting such a minimum too.
