### ISSUE TITLE
Mylyn build failures with timeout

### ISSUE THREAD

**Issue by ruspl-afed** [eclipse-mylyn/org.eclipse.mylyn#544]
We have repeatable timeout failures first appeared from https://ci.eclipse.org/mylyn/job/GitHub-mylyn-Orga/job/org.eclipse.mylyn/job/main/311/
Perhaps it is related with switch to Tycho 4.0.8, but I cannot state it.

These failures puts our final contribution to SimRel 2024-06 at risk

**Comment by merks** [comment]
yes, I think the timeout is too small:

**Comment by BeckerFrank** [comment]
I add another 10 minutes to the timeout option, so now we have 60 minutes.
The strange thing is that I have never seen the timeout in pull requests.

**Comment by merks** [comment]
PR builds don't do signing.  :stuck_out_tongue_winking_eye:

**Comment by merks** [comment]
At 56min 12s it's still close to the 60min threshold where a slow instance can still timeout, and that's after waiting a whole hour already...

**Comment by BeckerFrank** [comment]
new limit set with https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/547

**Comment by ruspl-afed** [comment]
Build statistics looks much better now, thanks @BeckerFrank and @merks
