### ISSUE TITLE
Eliminate long maven build from the setup

### ISSUE THREAD

**Issue by merks** [eclipse-mylyn/org.eclipse.mylyn#552]
I believe the maven build was added to address the problem with the errors in the org.eclipse.mylyn.wikitext.maven project.  Which made me wonder why an artifact in the .m2 cache is needed at all.  So I asked about here:

https://github.com/eclipse-m2e/m2e-core/discussions/1777#discussioncomment-9685967

Based on that answer, it seems to me that we can just add the m2e nature/builder to the two projects such that the two org.eclipse.mylyn.wikitext.maven  dependencies resolve to the workspace projects.

I can experiment further to verify that this fixes the problem.  I just wanted to confirm that there is no some other reason for doing a full build (which takes really long which is really quite annoying).

**Comment by ruspl-afed** [comment]
Thanks @merks please proceed with replacing full cli mvn build with what m2e can offer

**Comment by merks** [comment]
I've tested that this works well, but will retest after the commit.  Note I've just disabled the build so that one could locally enable it if desired...

**Comment by wimjongman** [comment]
Can this be closed?
