### ISSUE TITLE
Hudson Connector - AuthenticationException: Forbidden

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#57]
Created by Sebastian List: https://bugs.eclipse.org/bugs/show_bug.cgi?id=412596

=================================================================================
`Hi,
I experiencing authentication errors when trying to connect to a Hudson v3.0.0 server. I cannot refresh Build Plans, nor can I validate my settings. The Stacktrace reads as follows:

org.eclipse.core.runtime.CoreException: Unexpected error: Forbidden
	at org.eclipse.mylyn.internal.hudson.core.HudsonCorePlugin.toCoreException(HudsonCorePlugin.java:61)
	at org.eclipse.mylyn.internal.hudson.core.HudsonServerBehaviour.validate(HudsonServerBehaviour.java:908)
	at org.eclipse.mylyn.builds.internal.core.BuildServer.validate(BuildServer.java:369)
`

Sam Davis:
`hanks for the detailed bug report! It looks like the problem is that your server is not returning a 404 for /j_acegi_security_check - could you confirm what response you get when doing a GET to that URL? It's only when getting a 404 there that the connector tries /j_spring_security_check. Since we no longer support versions prior to 3.0.1 we should probably try the latter first and fall back to the former if it fails: https://git.eclipse.org/r/#/c/21655/. This appears to still work for Hudson 2.2.1.`

Sam Davis:
`Thanks. It sounds like providing the auth header might be a better solution, but it will be a while before we have time to look into that. It could help to speed this up if you submitted a code review. :)`

=================================================================================

I'm having the same problem with my Jenkins Docker instance, v2.391

Disable the 'CSRF Protecttion' "solution" is no longer an option.

**Comment by wimjongman** [comment]
Thanks for pulling this in, George.

**Comment by BeckerFrank** [comment]
Yes we need to change the authenticate to support CSRF Protection. This is a blocker for reactivate the HudsonTests
