### ISSUE TITLE
add junit  Rule for CIServer Tests

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#590]
We want to have a way that when we not run on CI Server tests get Ignored but on CI Server these tests should run.

**Comment by gnl42** [comment]
This change will do that, as long as the code uses the test setup classes.

**Comment by BeckerFrank** [comment]
> This change will do that, as long as the code uses the test setup classes.

Please look into the branch 590_Bugzilla_Rest_Connector .In build Job is green I create a pull request

**Comment by gnl42** [comment]
Looks very similar to my approach. 
 
I was planning on moving bugzilla unit tests to JUnit 5

**Comment by BeckerFrank** [comment]
I close this because we solve this with issue #51
