### ISSUE TITLE
Latest updatesite not updated anymore

### ISSUE THREAD

**Issue by sebthom** [eclipse-mylyn/org.eclipse.mylyn#6]
Last year I opened this ticket https://bugs.eclipse.org/bugs/show_bug.cgi?id=576634 asking for a stable URL to the latest mylyn release.
The answer was: https://download.eclipse.org/mylyn/docs/releases/3.0/ 

However this update site is now two releases behind the latest release. It contains 3.0.43 instead of 3.0.45.

**Comment by BeckerFrank** [comment]
This was a org.eclipse.mylyn.docs issue that is now fixed.
