### ISSUE TITLE
Connector authentication by token

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#62]
GitHub/Bamboo/Jira all have the requirement/option to authenticate by token instead of username/password.

The GitHub connector accomplishes this by kludging around the repository setup page code by detecting/intercepting the flow of the setup process.

It would be nice to have this option added to the base code so any connector can access the option, and make it less likely that any future code changes break the github connector

**Comment by mjmeijer** [comment]
Should we be encapsulating something like this in the commons code? https://github.com/auth0/java-jwt

**Comment by ruspl-afed** [comment]
I'm not sure what exactly do you mean by "encapsulate".

**Comment by mjmeijer** [comment]
Generalize token authentication in mylyn 'authentication' terms, like 'task' and 'rrpository' with reference implementation for github?
