### ISSUE TITLE
Rename Hudson connector to Jenkins connector

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#63]
Given that the Hudson project is no longer maintained, and announced as obsolete in 2017 (https://en.wikipedia.org/wiki/Hudson_(software))
And that the source code was archived Feb. 2021 (https://www.eclipse.org/projects/archives.php) .

I would like to suggest that the connector be renamed to Jenkins and any reference to Hudson be dropped.

**Comment by wimjongman** [comment]
Yes, good idea.

**Comment by wimjongman** [comment]
George, are you going to work on this?

**Comment by gnl42** [comment]
Hi Wim, @BeckerFrank grabbed it and is working on it

**Comment by BeckerFrank** [comment]
> Hi Wim, @BeckerFrank grabbed it and is working on it

@gnl42: You can continue if you want. The main reason was that I need to create a new branch 63-first-part-UI-change for a test that the GitHub webhooks are in place and work correctly. Fell free to delete this branch.

**Comment by gnl42** [comment]
@BeckerFrank  Sure. I'll start with your work.

I don't have permission to delete the branch though.

**Comment by BeckerFrank** [comment]
> @BeckerFrank Sure. I'll start with your work.
> 
> I don't have permission to delete the branch though.

I delete the branch 63-first-part-UI-change but have the branch for some days in my local repository.

**Comment by gnl42** [comment]
Thanks. I forked it earlier today.
Anything I shouldn't keep?

**Comment by BeckerFrank** [comment]
I only changed the parts that I found in the discovery and Hudson UI so feel free to use or start a fresh new branch.
If you want you can join us here https://chat-staging.eclipse.org/#/room/#tools.mylyn:matrix-staging.eclipse.org
