### ISSUE TITLE
Set java version to 17

### ISSUE THREAD

**Issue by gnl42** [eclipse-mylyn/org.eclipse.mylyn#66]
Can we set the java level to 17 given than Eclipse has been shipping with 17 for the last couple of releases, and 17 will be the base level for Eclipse 2023-06 (https://www.eclipse.org/lists/platform-dev/msg03746.html)

**Comment by akurtakov** [comment]
FYI it's already changed in I-builds https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/commit/fb5049c9570a9d2357bff64faf0db7203fbd8244 and there are already bundles requiring Java 17. 
+1000 from me for this.

**Comment by gnl42** [comment]
Can we at least start the process and move to 11 now?

**Comment by BeckerFrank** [comment]
Maybe we should look if we really need to include the 3 open issues in the [3.26.0](https://github.com/eclipse-mylyn/org.eclipse.mylyn/milestone/1) release or if we can start the first new release.

**Comment by gnl42** [comment]
It's a bit silly in that I need Java 11 to lunch Mylyn for debugging/testing yet the code is at 1.8

**Comment by wimjongman** [comment]
George, please go ahead if you want to make a PR to jump to 17.

**Comment by gnl42** [comment]
Hi Wim,
    sure, but if it requires any changes for the Jenkins builds I will 
need guidance
