### ISSUE TITLE
Where to find release notes?

### ISSUE THREAD

**Issue by sebthom** [eclipse-mylyn/org.eclipse.mylyn#7]
Release notes until Mylyn 3.25.2 can be found here https://www.eclipse.org/mylyn/new/all.php

Where are the release notes/changelogs for newer versions?

**Comment by BeckerFrank** [comment]
Mylyn 3.25.2 is the actual Release.
We plan to release 3.26 see https://github.com/eclipse-mylyn/.github/issues/5.
