### ISSUE TITLE
Fix duplicate working sets in the Oomph setup

### ISSUE THREAD

**Issue by merks** [eclipse-mylyn/org.eclipse.mylyn#72]
I think the error was introduced by this commit:

https://github.com/eclipse-mylyn/org.eclipse.mylyn/commit/d32955ca668afbf884fc78495690cd93a65fb55f

Please delete the second copy:

![image](https://user-images.githubusercontent.com/208716/228467867-21e3c1a6-9793-4725-a3e5-1934dc3c1699.png)

It's good to enable Live Validation to find such errors early:

![image](https://user-images.githubusercontent.com/208716/228468153-69a0f8cc-808b-4308-a91a-4fa3ce9562b2.png)

**Comment by BeckerFrank** [comment]
Fixed with Pull Request  https://github.com/eclipse-mylyn/org.eclipse.mylyn/pull/73

I have activate the Live Validation so hopefully I did not make the same mistake again.

**Comment by merks** [comment]
Thank you.  😀
