### ISSUE TITLE
Drop support for Gerrit Connector

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn#74]
Here the reasons.
- Eclipse is moving from git / Gerrit to GitHub / Gitlab
- the actual active Gerrit version is 3.5 or greater (see [Gerrit Supported Versions](https://www.gerritcodereview.com/support.html))
- the mylyn.org instances with version 2.11.10 or 2.13.8 do not work anymore (see Issue #26 we have failing Gerrit tests)

As a first step we remove the Gerrit Connector from the next Mylyn version (3.26).

**Comment by BeckerFrank** [comment]
The next step, deleting the source, is planned for after 3.26.

**Comment by wimjongman** [comment]
Can we/Should we isolate the connector in a separate repo?

**Comment by ruspl-afed** [comment]
Perhaps we should not. I consider the drop of Gerrit support as a decision forced by limited resources.
However mylyn.gerrit subfolder could be good.
